### ISSUE TITLE
BTC transaction history not displayed

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#10]
![screenhunter_04 feb 27 17 28](https://cloud.githubusercontent.com/assets/4045519/6410043/029bbdc2-bea6-11e4-8b62-1964f173b588.jpg)

For Counterparty assets one can see history of transactions, but for BTC that's not possible (although each of the addresses has a non-zero BTC balance)

**Comment by ouziel-slama** [comment]
That is for 2 reasons:
1) the counterparty database doesn't store only BTC transactions
2) for a classical BTC transaction is difficult to define one `source` and one  `destination`..

That mean this screen can not contains the same things as the other assets..

**Comment by ouziel-slama** [comment]
see here: https://github.com/CounterpartyXCP/counterparty-gui/commit/36433dc0190fa60f134a0446486f8bc8b2d8c2cd
