### ISSUE TITLE
Improve handling of network disconnect

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#17]
I don't know how hard it is to do, but currently if `counterparty-server` stops, GUI enters the "not responding" mode similar to when a Windows application hangs.

**Comment by ouziel-slama** [comment]
I'am not sure if there is another solution but put a low time out (2 or 3 seconds for instance).

**Comment by ouziel-slama** [comment]
moved here: https://github.com/CounterpartyXCP/counterparty-gui/issues/41
