### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#26]
Use font.pointSize instead of pixelSize?
See http://qt-project.org/forums/viewthread/27201
Or maybe add `Preferences > Settings > Font Type/Size`?

On my Window fonts are a bit small. 

This is related to accessibility requirements from https://github.com/CounterpartyXCP/counterparty-gui/issues/15

**Comment by ghost** [comment]
Fonts are definitely too small. (ESPECIALLY the buttons!) +1

**Comment by ouziel-slama** [comment]
fixed
