### ISSUE TITLE
Export transaction history

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#29]
This is what people frequently ask for.
If it's too complicated to easily implement in the GUI, we can consider one of these:
- Support > Transactions > runs a CLI command to export all Counterparty-related transactions to a CSV file and prompts to "Save as...". This would be very nice.
- Support > Debug console > here people could run the same command on their own and we wouldn't need to do anything (but we'd have to have a Debug console

**Comment by ouziel-slama** [comment]
duplicate with https://github.com/CounterpartyXCP/counterparty-gui/issues/40
Thre is also the option `--json-output` with `counterparty-client`. If there is frequents asks we can add an option `--csv-output`.
