### ISSUE TITLE
Increase menu bar height, add icons?

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#31]
![image](https://cloud.githubusercontent.com/assets/4045519/6438037/416aa296-c100-11e4-95c8-4eea22af6f21.png)

It's tiny in proportion to my screen (maybe 1/30th of my screen vertical resolution).
If icons could be added, that'd be even better to make it easier to click on menu items without having to aim too precisely.

**Comment by ghost** [comment]
In RC2:
![toa](https://cloud.githubusercontent.com/assets/4045519/6462057/b2fe584a-c1e0-11e4-970d-387cee70a367.png)
- Manual adjustments are required
- Not everything was resized (maybe it should be that way?)
- Upon restart app doesn't remember previous adjustments so it has to be redone

By the way, I'm using 1680x1050 and Small (100%) (default font size).

Another side effect is that font at the bottom is bigger than the bar (not always, but after one of those "refresh" issues - https://github.com/CounterpartyXCP/counterparty-gui/issues/27).
![image](https://cloud.githubusercontent.com/assets/4045519/6462137/79c2c362-c1e1-11e4-8462-fef5851e29df.png)

**Comment by ouziel-slama** [comment]
Font issue fixed, and table issues moved here https://github.com/CounterpartyXCP/counterparty-gui/issues/40
