### ISSUE TITLE
Side menu probably not enough to display assets with long-names

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#32]
![image](https://cloud.githubusercontent.com/assets/4045519/6438070/9baf5f44-c100-11e4-8a74-62240a41b22e.png)
- It's not possible to resize it
- Assets with longer names (e.g. alphanumeric assets) and large amounts (say, > 1 million) probably can't be displayed in the GUI

**Comment by ouziel-slama** [comment]
The side menu is resized automatically: asset name and amounts are always visible.
