### ISSUE TITLE
--verbose for debugging?

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#33]
Would it be useful to add a `--verbose` option so that log is output to the console (similar to `counterparty-client`) if GUI is started that way?

**Comment by ouziel-slama** [comment]
This parameter already exists. I also add a log file for debugging:
https://github.com/CounterpartyXCP/counterparty-gui/commit/3621b7a079b880bcac62396796450c4b82c6789e

**Comment by ghost** [comment]
Great. I tried `--help` to see what might exist, but I should have looked at source code.
