### ISSUE TITLE
Option to use the default values for all server, port, username

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#34]
This is just an idea for a marginal improvement in user friendliness that is probably not necessary in v1.0.
- Use the same server bitcoin and counterparty server  (default: ON)
- Use the default ports (default: ON)
- Use the default username (default: ON)

If unchecked, then different servers/ports/accounts could be used.
That could make switching and setting wallet faster and more convenient.
If defaults are encouraged, then switching to a different server (even automatically) could become less painful and in the future if multiple servers could be set in order of priority, automatic switching in case of dropped connection would be easier to setup.

**Comment by ouziel-slama** [comment]
What is planned to make the GUI immediately usable is:
- make available by default an open public Couterparty server
- add a wrapper for a BIP32 wallet compatible with Counterwallet

Then users will just need to enter (or create) a passphrase.

**Comment by ouziel-slama** [comment]
you can use `-config-file` parameter.
also see https://github.com/CounterpartyXCP/counterparty-cli/issues/35
