### ISSUE TITLE
Enable online help in Preferences

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#37]
Can the little `?` thing be enabled with some basic online help/hint info?
I don't know if on-hover hints can be added without having help pages - that would already be quite useful and save a few trips to the forums/docs.

![image](https://cloud.githubusercontent.com/assets/4045519/6462244/6ff46074-c1e2-11e4-8d0c-23bfa1618be6.png)

**Comment by ouziel-slama** [comment]
I remove this button (it is Windows specific).
Duplicate with https://github.com/CounterpartyXCP/counterparty-gui/issues/23
