### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by pryds** [CounterpartyXCP/counterparty-gui#6]
I see you support MacOS X for the moment and seem to plan including Windows (as per build instructions in README.md file). Any plans to also support Linux in the future?

**Comment by ghost** [comment]
I think Linux users would be comfortable using the cli? (At least I would..)

**Comment by pryds** [comment]
I think Linux users come in many variations ;-)

Or maybe that's just me. Sure, I'm not afraid of the cli, and would prefer it for complicated tasks, but for everyday use with a wallet I'd prefer just clicking a button.

**Comment by ghost** [comment]
It seems that Linux is actually supported:

Configuration file
"Linux  ~/.config/counterpartygui/counterpartygui.conf"

**Comment by ouziel-slama** [comment]
@pryds: yes there is no problem to use the GUI in Linux.
@goodtaster: the configuration file is now the same as `counterparty-client` (`~/.config/counterparty/client.conf`).
