### ISSUE TITLE
(Holding) 'type' change to 'Source', 'swap' to 'exchange'?

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#7]
As subject.

`swap` could be `exchange` (or `trade`, although I prefer `exchange`).

**Comment by ouziel-slama** [comment]
hum.. I'am not sure we talk about the same thing. Here `swap` means the `source` and the `destination` address belong to your wallet.

**Comment by ghost** [comment]
Ah... Okay. I didn't remember how I got those testnet coins, it was a while ago.
For that purpose I'd still use some other word. Maybe `rebalance` (as in portfolio rebalancing)? 

Swap sounds like A was swapped for B. While you could say that the holding address for the `asset` was swapped, it's still slightly confusing.

**Comment by adamkrellenstein** [comment]
'redistribute' or 'in-wallet'?

**Comment by ghost** [comment]
`in-wallet` sounds good to me

**Comment by ouziel-slama** [comment]
done here: https://github.com/CounterpartyXCP/counterparty-cli/commit/bdb3ac2e86a9ab7cfe22f222a092e2b3094d31a3
