### ISSUE TITLE
Advanced options: "use testnet network" seems redundant?

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#8]
I am using the testnet network but I didn't check it. 

I assume that this might be for the case one's creds are the same so it only appends `--testnet` to connect, but I'm not sure.

**Comment by ouziel-slama** [comment]
yeah when you check `testnet`, you should ensure the credentials (and port) are for a testnet server..
I'am surprised that the GUI works well without checking it! I will check that. In any case we need it for distant public server (when you just select an host in the first tab)

**Comment by ghost** [comment]
Well it works well as long as you change the ports 14000/18332 - I like that :-)
Although from the usability perspective one shouldn't need to know those port numbers, so that's something that can be considered as well.

Later on, I would prefer to be able to `Browse` and pick 2 config files (i.e. `client.conf` and `client.testnet.conf`) rather than have a `Testnet ON/OFF` switch (with a single config file and password), but it seems the intent is to have that switch.
Alternatively, if one can start the GUI with a `--config-file` (similar to `counterparty-client`), that would be great, then I could simply create multiple shortcuts, while those who need to occasionally switch to testnet could use the `ON/OFF` checkbox.

**Comment by ouziel-slama** [comment]
> Well it works well as long as you change the ports 14000/18332 - I like that :-)

@rippler, did you try to make a transaction? I think that can not works without the `testnet` params.

> Although from the usability perspective one shouldn't need to know those port numbers, so that's something that can be considered as well.

hum seems difficult to ride those parameter... but you can leave them blank, then `counterparty-gui` will use default ports..

> Alternatively, if one can start the GUI with a --config-file

You can already use the `config-file` params. Also if you put an empty values for port, and if the host/credentials are the same for testnet and mainnet, you can for instance use `./counterparty-gui.py --testnet`.

**Comment by ghost** [comment]
> @rippler, did you try to make a transaction? I think that can not works without the testnet params.

Yes, just now. Worked fine once. I set ports to testnet ports and no need to check "Use testnet network".
Then I got error code -25.
It actually does work (I think I made 2 transactions) but mostly it doesn't. I post details if I find out how to repro.

**Comment by ghost** [comment]
I can send it a number of times in a row, it works every time without the testnet option checked (the video is looping, only one send is recorded, but I did try 4 times in a row). I also checked CP testnet log - success.

![no-testnet-testnet](https://cloud.githubusercontent.com/assets/4045519/6416202/5aa1eada-bedf-11e4-9306-42ff30485521.gif)
